### ISSUE TITLE
Reason for invalid subdomain matching with sub-domain rule specified in RFC 5321

### ISSUE THREAD

**Issue by adro1999** [ldthomas/apg-java#12]
Hello,

I generated a parser class with apg for SMTP greeting messages according to the rules specified in RFC 5321. However, when I tested the parser and looked at the trace, it seemed to me that the rule 'sub-domain     = Let-dig [Ldh-str]' with 'Let-dig        = ALPHA / DIGIT' and 'Ldh-str        = *( ALPHA / DIGIT / "-" ) Let-dig', was not properly executed. When I looked through the examples you provided, I randomly noticed that you commented out the original 'sub-domain' and 'Ldh-str' rules from RFC 5321 in the 'mailbox.bnf' and replaced them with other rules, which then properly parsed my greeting message when I tested them. I am just curious to know, if you remember why you had to modify these two rules.  I am just getting into ABNF parsing and want to know if the failure results from the side of apg or if these rules arent properly defined in the RFC.

Thank you in advance

**Comment by ldthomas** [comment]
APG does not generate strictly context-free parsers. It uses two simplifications that, in my opinion at least, make the parsers not only easier to manage but make the grammars easier to write and understand. I'm sure there are other opinions. One problem, of course, is that most RFC ABNF grammars assume fully context-free parsing. Therefore, they often need to be "tweaked" for APG.

The first is "first-success disambiguation" - that is, alternates are tried left to right and the first successful alternate is accepted and any remaining alternates are ignored. This avoids ambiguous parse trees.

The second (and related simplification), and the one that is relevant to your problem, is "greedy repetitions". That is, repetitions match the longest possible string and never backtrack to try shorter matches. The simplest example is the grammar
> S = *"a" "a"  

For the input string "aaa" a fully context-free parser would first match "aaa" then fail to match the final "a", then backtrack and try matching "aa" and then succeed matching the final "a". With "greedy repetitions", "aaa" is matched and then the parse fails because of the remaining "a".

With the `sub-domain` rule they are attempting to allow strings of letters, digits and hyphens but prevent hyphens from appearing first or last in the string. With
> Ldh-str    	= *( ALPHA / DIGIT / "-" ) Let-dig  

"greedy repetitions" will cause the first term to suck up the entire remainder of the string and `Let-dig` will always fail.

My redefinition of `sub-domain` avoids this problem.

**Comment by adro1999** [comment]
Thank you for your fast and detailled answer
